# Generated by Django 3.1.2 on 2020-10-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'market'), (2, 'limit'), (3, 'stop-loss')]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'purchase'), (2, 'sale')]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'market'), (2, 'limit'), (3, 'stop-loss')]),
        ),
    ]
