# Generated by Django 3.1.2 on 2020-10-15 10:40

from django.db import migrations


def check_demand(apps, schema_editor):
    Item = apps.get_model('trading_app', 'Item')
    Offer = apps.get_model('trading_app', 'Offer')
    avg = Offer.objects.count() / Item.objects.count()
    for item in Item.objects.select_related('offer').all():
        if item.offer.count() >= avg:
            item.demanded = True
        else:
            item.demanded = False
        item.save(update_fields=('demanded', ))


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_auto_20201015_1039'),
    ]

    operations = [

    ]
