# Generated by Django 3.1.2 on 2020-10-15 11:29

from django.db import migrations
from django.db.models import Subquery, OuterRef, Case, When, Count, BooleanField


def check_demand(apps, schema_editor):
    Item = apps.get_model('trading_app', 'Item')
    Offer = apps.get_model('trading_app', 'Offer')
    avg = Offer.objects.count() / Item.objects.count()
    Item.objects.update(demanded=Subquery(
        Item.objects.filter(
            id=OuterRef('id')
        ).annotate(
            offers_count=Count('offer'),
            _demanded=Case(
                When(offers_count__gte=avg, then=True),
                default=False,
                output_field=BooleanField()
            )
        ).values('_demanded')[:1]
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0006_auto_20201015_1040'),
    ]

    operations = [
        migrations.RunPython(check_demand)
    ]
