version: '3.7'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    restart: on-failure
    build: .
    volumes:
      - .:/code
    links:
      - db:db
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
     - web-variables.env
    command: python /code/manage.py runserver 0.0.0.0:8000
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    container_name: 'redis'
  celery:
    build: .
    command: celery -A trading worker -l info
    env_file:
      - web-variables.env
    depends_on:
      - redis
      - web
volumes:
  postgres_data: