version: '3.7'
services:
  db:
    image: postgres
    container_name: db
    env_file:
      - web-variables.env
  web:
    restart: on-failure
    build: .
    volumes:
      - .:/code
    links:
      - db:db
    depends_on:
      - db
    env_file:
     - web-variables.env
    entrypoint: ["./docker-entrypoint.sh"]
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    container_name: 'redis'
  celery:
    build: .
    command: celery -A trading worker -B
    env_file:
      - web-variables.env
    depends_on:
      - redis
      - web
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
volumes:
  postgres_data: