version: '3.7'
services:
  db:
    image: postgres
    env_file:
      - web-variables.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/opt/services/djangoapp/static
    depends_on:
      - db
    env_file:
     - web-variables.env
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    volumes:
    - .trading-redis:/data
  celery:
    build: .
    command: celery -A trading worker -B
    env_file:
      - web-variables.env
    depends_on:
      - redis
      - web
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static
    depends_on:
      - web
volumes:
  static_volume: